### PR TITLE
Use fixed-resample for proper input stream resampling

### LINKED ISSUE #9: Proper resampling in the `InputProxy`
Currently, the `InputProxy` uses a crude linear resampling method, which is fast enough and IMHO is okay for resampling 44.1 kHz <-> 48 kHz, but we should definitely improve the quality of the resampling, maybe choosing the resampling strategy depending on the requested ratio.

Look into [`fixed-resample`](https://github.com/MeadowlarkDAW/fixed-resample) for a potential ready-made solution.

### LINKED ISSUE #11: Drift correction for emulated Duplex streams
Currently, the manual/emulated Duplex stream created from `interflow::duplex::create_duplex_stream` assumes that the separate input and output streams are already synchronized.

Implement drift measurement and correction.

### PR DESCRIPTION
**Pull request by SolarLiner**
## Description

Integrates `fixed-resample` to accurately resample the input stream in the duplex system.

Closes #9

Closes #11

## Type of Change

Please delete options that are not relevant.

- [x] Feature addition

## How Has This Been Tested?

Not sure how to test this, but I have added a loopback example to head the input into the output.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Wherever possible, I have added tests that prove my fix is effective or that my feature works. For changes that need to be validated manually (i.e. a new audio driver), use examples that can be run to easily validate them.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

File: src/duplex.rs [hunk 1]
```diff
@@ -35,8 +37,29 @@ pub struct DuplexStream<Callback, Error> {
 
 /// Input proxy for transferring an input signal to a separate output callback to be processed as a duplex stream.
 pub struct InputProxy {
-    buffer: rtrb::Producer<f32>,
-    output_sample_rate: Arc<AtomicU64>,
+    producer: Option<fixed_resample::ResamplingProd<f32, MAX_CHANNELS>>,
+    receive_output_samplerate: rtrb::Consumer<u32>,
```
Comment (geom3trik) [inline src/duplex.rs:41]: Is using a ring buffer just to send a sample rate better than using an atomic?

File: src/duplex.rs [hunk 2]
```diff
@@ -50,71 +73,73 @@ impl AudioInputCallback for InputProxy {
...
+                output_samplerate,
+                num_channels.get()
+            );
+            let (tx, rx) = fixed_resample::resampling_channel(
+                num_channels,
+                input_samplerate,
+                output_samplerate,
+                ResamplingChannelConfig {
+                    latency_seconds: 0.01,
+                    quality: fixed_resample::ResampleQuality::Low,
```
Comment (geom3trik) [inline src/duplex.rs:95]: Later I see that this is configurable. Does it not need to be configurable here?

**Review by geom3trik — APPROVED** [review]

File: src/duplex.rs (hunk 1 above)
Comment (SolarLiner) [reply src/duplex.rs:41]: I'd need to have a separate signaling atomic for new values, this is similar to that but already self-contained, and we already have the dependency on `rtrb`, so I think it's fine

File: src/duplex.rs (hunk 2 above)
Comment (SolarLiner) [reply src/duplex.rs:95]: This is a question I've been asking myself -- should we expose the configuration or should we make this seamless to the user? There's an argument for providing good defaults but exposing the setting, but it might also be confusing to have those options available.

I myself don't know if I can set the `latency_seconds` to zero, theoretically I should be able to and `fixed_resample` will try to get the lowest latency it can, but also it might just break, and exposing that to the user feels like exposing footguns.

I think I'm leaning towards providing the configuration with good defaults, but not for latency which if it works I'll keep at 0 because I don't think it makes sense to have anything else (I'll probably ask on Discord about it though).
